services:
  api:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/tabs?sslmode=disable
      PORT: 8888
    volumes:
      - "./secrets:/secrets:ro"
    ports:
      - "8888:8888"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tabs
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "55432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
