version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tabs
    volumes: ["./.pg:/var/lib/postgresql/data"]
    ports: ["5432:5432"]

  api:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/tabs?sslmode=disable
    volumes:
      - "./secrets:/secrets:ro"
    ports: ["8080:8080"]
    depends_on: [db]
