services:
  api:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/tabs?sslmode=disable
      PORT: 8888
    volumes:
      - "./secrets:/secrets:ro"
    ports:
      - "8888:8888" 
    depends_on: [db]
